### ISSUE TITLE
jsii maven target fails with jsii-pacmak@1.0.0

### ISSUE THREAD

**Issue by jsdtaylor** [elegantdevelopment/aws-cdk-dynamodb-seeder#10]
**Describe the bug**
`Failed to collect dependencies for uk.co.elegantdevelopment:aws-cdk-dynamodb-seeder:jar:1.3.3: Could not resolve version conflict among [...]`

**To Reproduce**
`make`

**Expected behavior**
Should create maven artefact(s) in `/dist/java`

**Evidence**
```sh
> jsii-pacmak

[jsii-pacmak] [WARN] Exception occurred, not cleaning up /var/folders/vh/1p1_c0fx3dj9hhdh1nd8wkd40000gn/T/npm-packTrnfE6
Error: Process exited with status 1
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] uk.co.elegantdevelopment:aws-cdk-dynamodb-seeder                   [jar]
[INFO] aggregatepom                                                       [pom]
[INFO] 
[INFO] ----------< uk.co.elegantdevelopment:aws-cdk-dynamodb-seeder >----------
[INFO] Building uk.co.elegantdevelopment:aws-cdk-dynamodb-seeder 1.3.3    [1/2]
[INFO] --------------------------------[ jar ]---------------------------------

...

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] uk.co.elegantdevelopment:aws-cdk-dynamodb-seeder 1.3.3 FAILURE [ 36.077 s]
[INFO] aggregatepom 1.0.0 ................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  36.183 s
[INFO] Finished at: 2020-02-26T17:04:44Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project aws-cdk-dynamodb-seeder: Could not resolve dependencies for project uk.co.elegantdevelopment:aws-cdk-dynamodb-seeder:jar:1.3.3: Failed to collect dependencies for uk.co.elegantdevelopment:aws-cdk-dynamodb-seeder:jar:1.3.3: Could not resolve version conflict among [software.amazon.awscdk:dynamodb:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:applicationautoscaling:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:autoscaling-common:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:dynamodb:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:applicationautoscaling:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:dynamodb:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:cloudformation:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:dynamodb:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:cloudwatch:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:dynamodb:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:iam:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:cdk-region-info:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:dynamodb:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:iam:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:dynamodb:jar:[1.26.0,2.0.0) -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:lambda:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:ec2:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:ssm:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:lambda:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:ec2:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:lambda:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:events:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:lambda:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:logs:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:lambda:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:s3-assets:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:cdk-assets:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:lambda:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:s3-assets:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:lambda:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:sqs:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:lambda:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:cdk-cx-api:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:lambda:jar:[1.26.0,2.0.0) -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:s3:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:kms:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:s3:jar:[1.26.0,2.0.0) -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:s3-deployment:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:cloudfront:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:certificatemanager:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:route53:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:s3-deployment:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:cloudfront:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:certificatemanager:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:s3-deployment:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:cloudfront:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:s3-deployment:jar:[1.26.0,2.0.0) -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:core:jar:[1.26.0,2.0.0) -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:cdk-customresources:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:sns:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:cdk-customresources:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:stepfunctions:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:cdk-customresources:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:stepfunctions-tasks:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:ecr:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:cdk-customresources:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:stepfunctions-tasks:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:ecr-assets:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:cdk-customresources:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:stepfunctions-tasks:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:ecs:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:autoscaling:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:cdk-customresources:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:stepfunctions-tasks:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:ecs:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:autoscaling-hooktargets:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:sns-subscriptions:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:cdk-customresources:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:stepfunctions-tasks:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:ecs:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:autoscaling-hooktargets:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:cdk-customresources:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:stepfunctions-tasks:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:ecs:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:elasticloadbalancing:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:cdk-customresources:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:stepfunctions-tasks:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:ecs:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:elasticloadbalancingv2:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:cdk-customresources:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:stepfunctions-tasks:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:ecs:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:route53-targets:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:apigateway:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:cdk-customresources:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:stepfunctions-tasks:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:ecs:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:route53-targets:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:cdk-customresources:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:stepfunctions-tasks:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:ecs:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:secretsmanager:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:sam:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:cdk-customresources:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:stepfunctions-tasks:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:ecs:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:secretsmanager:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:cdk-customresources:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:stepfunctions-tasks:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:ecs:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:servicediscovery:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:cdk-customresources:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:stepfunctions-tasks:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:ecs:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:cdk-customresources:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:stepfunctions-tasks:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:cdk-customresources:jar:[1.26.0,2.0.0) -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.jsii:jsii-runtime:jar:[1.0.0,2.0.0)] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException


    at ChildProcess.<anonymous> (/Users/jtaylor/Code/src/github.com/elegantdevelopment/aws-cdk-dynamodb-seeder/node_modules/jsii-pacmak/lib/util.js:57:31)
    at Object.onceWrapper (events.js:313:26)
    at ChildProcess.emit (events.js:223:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aws-cdk-dynamodb-seeder@1.3.3 package: `jsii-pacmak`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the aws-cdk-dynamodb-seeder@1.3.3 package script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Additional context**
None

**Comment by jsdtaylor** [comment]
Full log line:

`[ERROR] Failed to execute goal on project aws-cdk-dynamodb-seeder: Could not resolve dependencies for project uk.co.elegantdevelopment:aws-cdk-dynamodb-seeder:jar:1.3.3: Failed to collect dependencies for uk.co.elegantdevelopment:aws-cdk-dynamodb-seeder:jar:1.3.3: Could not resolve version conflict among [software.amazon.awscdk:dynamodb:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:applicationautoscaling:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:autoscaling-common:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:dynamodb:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:applicationautoscaling:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:dynamodb:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:cloudformation:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:dynamodb:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:cloudwatch:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:dynamodb:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:iam:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:cdk-region-info:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:dynamodb:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:iam:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:dynamodb:jar:[1.26.0,2.0.0) -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:lambda:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:ec2:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:ssm:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:lambda:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:ec2:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:lambda:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:events:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:lambda:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:logs:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:lambda:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:s3-assets:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:cdk-assets:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:lambda:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:s3-assets:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:lambda:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:sqs:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:lambda:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:cdk-cx-api:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:lambda:jar:[1.26.0,2.0.0) -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:s3:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:kms:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:s3:jar:[1.26.0,2.0.0) -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:s3-deployment:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:cloudfront:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:certificatemanager:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:route53:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:s3-deployment:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:cloudfront:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:certificatemanager:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:s3-deployment:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:cloudfront:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:s3-deployment:jar:[1.26.0,2.0.0) -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:core:jar:[1.26.0,2.0.0) -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:cdk-customresources:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:sns:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:cdk-customresources:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:stepfunctions:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:cdk-customresources:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:stepfunctions-tasks:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:ecr:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:cdk-customresources:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:stepfunctions-tasks:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:ecr-assets:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:cdk-customresources:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:stepfunctions-tasks:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:ecs:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:autoscaling:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:cdk-customresources:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:stepfunctions-tasks:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:ecs:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:autoscaling-hooktargets:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:sns-subscriptions:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:cdk-customresources:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:stepfunctions-tasks:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:ecs:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:autoscaling-hooktargets:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:cdk-customresources:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:stepfunctions-tasks:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:ecs:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:elasticloadbalancing:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:cdk-customresources:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:stepfunctions-tasks:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:ecs:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:elasticloadbalancingv2:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:cdk-customresources:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:stepfunctions-tasks:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:ecs:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:route53-targets:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:apigateway:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:cdk-customresources:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:stepfunctions-tasks:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:ecs:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:route53-targets:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:cdk-customresources:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:stepfunctions-tasks:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:ecs:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:secretsmanager:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:sam:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:cdk-customresources:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:stepfunctions-tasks:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:ecs:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:secretsmanager:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:cdk-customresources:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:stepfunctions-tasks:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:ecs:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:servicediscovery:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:cdk-customresources:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:stepfunctions-tasks:jar:[1.26.0,1.26.0] -> software.amazon.awscdk:ecs:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:cdk-customresources:jar:[1.26.0,2.0.0) -> software.amazon.awscdk:stepfunctions-tasks:jar:[1.26.0,1.26.0] -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.awscdk:cdk-customresources:jar:[1.26.0,2.0.0) -> software.amazon.jsii:jsii-runtime:jar:[0.22.0,0.23.0), software.amazon.jsii:jsii-runtime:jar:[1.0.0,2.0.0)] -> [Help 1]`

**Comment by jsdtaylor** [comment]
Raised https://github.com/aws/jsii/issues/1295

**Comment by jsdtaylor** [comment]
Stale issue
